name: index_generator
description: Automatically generate index / barrel / library files with all the export needed for your library.
version: 3.4.0
homepage: https://github.com/BreX900/index_generator

# dart pub publish --dry-run

scripts:
  publish: dart pub publish
  # To generate .g files:
  build:runner:  dart run build_runner watch --delete-conflicting-outputs

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  console: ^4.1.0
  args: ^2.3.1

  path: ^1.8.1

  yaml: ^3.1.1
  checked_yaml: ^2.0.1
  mek_data_class: ^1.0.1
  json_annotation: ^4.8.0
  glob: ^2.1.0

  pubspec: ^2.2.0
  dart_style: ^2.2.3

dev_dependencies:
  lints: ^2.0.0

  test: ^1.21.6

  build_runner: ^2.3.3
  mek_data_class_generator: ^1.1.1
  json_serializable: ^6.6.1

executables:
  index_generator:

index_generator:
  exclude:
    - '**.g.dart'
    - '{_,**/_}*.dart'
  indexes:
    - path: lib
      disclaimer: false
      docs: |
        Automatically generate index / barrel / library files
        with all the export needed for your library.
