name: index_generator
description: Automatically generate index / barrel files with all the export needed for your library.
version: 2.0.0
homepage: https://github.com/BreX900/index_generator

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test:

index_generator:
  filters:
    - black: (^\_.*$)|(.*\/_.*)
    - black: .*.g.dart$
  indexes:
    # Default index and library name
    - path: example
    # Custom index and library name
    - path: example
      name: custom_index_name
      library: custom_library_name
    # Custom index and library name
    - path: example
      name: export_folders
      export:
        - example/src
