name: index_generator
description: Automatically generate index / barrel / library files with all the export needed for your library.
version: 3.2.0+1
homepage: https://github.com/BreX900/index_generator

# dart pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  console: ^4.1.0
  args: ^2.3.0

  path: ^1.8.1

  yaml: ^3.1.0
  checked_yaml: ^2.0.1
  json_annotation: ^4.4.0
  glob: ^2.0.2

  pubspec: ^2.0.1
  dart_style: ^2.2.3

dev_dependencies:
  lints: ^1.0.1

  test: ^1.20.1

  # To generate .g files:
  # dart run build_runner build --delete-conflicting-outputs
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.7
  json_serializable: ^6.1.3


