name: index_generator
description: Automatically generate index / barrel files with all the export needed for your library.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.2
  path: ^1.7.0
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

index_generator:
  filters:
    - black: (^\_.*$)|(.*\/_.*)
    - black: .*.g.dart$
  folders:
    - path: example
      library: false
    - path: lib
      index_name: main
      library: index_generator