name: index_generator
description: Automatically generate index / barrel files with all the export needed for your library.
version: 1.0.1
homepage: https://github.com/BreX900/index_generator

# flutter pub publish --dry-run

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2

index_generator:
  filters:
    - black: (^\_.*$)|(.*\/_.*)
    - black: .*.g.dart$
  folders:
    - path: example
      library: false
    - path: lib
      index_name: main
      library: index_generator