name: Test
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dart
        uses: dart-lang/setup-dart@v1

      - name: Fetch dependencies
        run: dart pub get

      - name: Test package
        run: dart test